### ISSUE TITLE
paste command not working

### ISSUE THREAD

**Issue by ankit-sinha-18** [hellmrf/PastebinTGBot#3]
I started your bot (@PastebinTGBot) ,,It is responding on /help command.
But when I used /paste Hello world. It didn't respond.

**Comment by hellmrf** [comment]
Please, check if you're using the correct Pastebin API_key. If so, post the logs, please.

EDIT: I'm sorry, I think I got it wrong. The hosted version ([@PastebinTGBot](https://t.me/PastebinTGBot)) is responding well right now.

**Comment by ankit-sinha-18** [comment]
![Uploading Screenshot_2020_1226_210631.jpg…]()
Please check,your bot (https://t.me/PastebinTGBot) is not responding on paste command

**Comment by ankit-sinha-18** [comment]
![Screenshot_2020_1226_210631](https://user-images.githubusercontent.com/72637068/103154610-84110b80-47be-11eb-96c8-41160774bb95.jpg)
Please check,your bot (https://t.me/PastebinTGBot) is not responding on paste command

**Comment by hellmrf** [comment]
I've checked the logs and found that it's presumable that your account has no username (@username), which seems to be a problem so far. I'll try to fix this, but for now, maybe you can try adding a username and try again. Thank you for the issue!
